# Generated by Django 4.1 on 2022-08-29 07:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=50)),
                ('main_img', models.ImageField(upload_to='photos/')),
                ('category_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-category_created'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_images', models.ImageField(upload_to='photos/')),
                ('img_uploaded', models.DateTimeField(auto_now_add=True)),
                ('photo_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.photocategory')),
            ],
            options={
                'ordering': ['-img_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='AllPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='all/')),
                ('image_credit', models.CharField(blank=True, max_length=100)),
                ('headline', models.CharField(max_length=300)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('embed', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.category')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
