# Generated by Django 4.1 on 2022-09-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(max_length=300),
        ),
    ]
